name: CI

on:
  push:

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
  
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  